server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: exam-service
          uri: lb://EXAM-SERVICE
          predicates:
            - Path=/exams/**

        - id: submission-service
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/submissions/**

        - id: evaluation-service
          uri: lb://EVALUATION-SERVICE
          predicates:
            - Path=/evaluations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: ${JWT_SECRET:EduAssessSuperSecretKeyForDevelopmentOnly2026}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

management:
  endpoints:
    web:
      exposure:
        include: health,info